apiVersion: apps/v1
kind: Deployment
metadata:
  name: robochefweb-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: robochef
  template:
    metadata:
      labels:
        app: robochef
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
